export const GET_USERINFO = 'GET_USERINFO'
export const SAVE_GEOHASH = 'SAVE_GEOHASH'
export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const ADD_CART = 'ADD_CART'
export const REDUCE_CART = 'REDUCE_CART'
